BlogProject/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')), 
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path 

from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'), 
    path('register/', views.register, name = 'register'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('search/', views.search, name = 'search'),
    path('create/', views.createPost, name='create'), 
    path('delete/<int:pk>/', views.deletePost, name='delete'),
    path('update/<int:pk>/', views.updatePost, name='update'),
    path('<slug:post>/', views.postDetail, name='postDetail'), 
    path('category/<str:category>/', views.category_list, name='category_list')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.expressions import OrderBy 
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify



def user_directory_path(inst, file_name):
	return f'posts/{inst.id}/{file_name}'


def get_registred_user(request):
	loged_user = request.user 
	return loged_user

class Category(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return f'{self.name}'

class Post(models.Model):
	CHOICES = (
		('published', 'Published'), 
		('draft', 'Draft'),
	)

	title = models.CharField(max_length=50)
	content = models.TextField(max_length = 1000)
	auther = models.ForeignKey(User, on_delete=models.CASCADE)
	status = models.CharField(max_length=10, choices=CHOICES, default='publish')
	# slug = models.AutoSlugField(populate_from = ['title',], unique_for_date='created', null=True)
	category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
	image = models.ImageField(upload_to = user_directory_path, default='posts/default.jpg')
	published = models.DateTimeField(default=timezone.now)
	updated = models.DateTimeField(auto_now = True)
	created = models.DateTimeField(auto_now_add=True)
	slug = models.SlugField(unique_for_date='created')


	def get_absolute_url(self):
		return reverse('blog:postDetail',args=[self.slug])

	class Meta:
		ordering = ('-published',)

	def __str__(self):
		return self.title 


	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		self.status = 'published'
		super(Post, self).save(*args, **kwargs)


class Comment(models.Model):
	post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
	content = models.TextField()
	published = models.DateTimeField(auto_now_add=True)
	status = models.BooleanField(default=True)
	name = models.CharField(max_length=100)


	class Meta:
		ordering = ('published',)


	def __str__(self):
		return f'Comment by {self.name}'

blog/forms.py
from django import forms
from django.db.models import fields
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.models import model_to_dict

from .models import Comment, Post 



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ("content",)



class SearchForm(forms.Form):
    q = forms.CharField()


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post 
        fields = ['title', 'content',  'category', 'image']



class UpdatePostForm(forms.ModelForm):
    class Meta:
        model = Post 
        fields = ['title', 'content', 'category', 'image']


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


    class Meta:
        model = User 
        fields = ['username', 'email', 'password1', 'password2']
       
       
        # doesn't work for password 
        # help_texts = {
        #     'username':None, 
        #     'email':None,
        #     'password':None, 
        #     'password2':None,
        # }

    

blog/views.py
from typing import Callable
from django.db.models.query import RawQuerySet
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required


from .models import Category, Post, Comment
from .forms import CommentForm, SearchForm, CreatePostForm, UpdatePostForm, NewUserForm
from .decorators import * 

def home(request):
    allPosts = Post.objects.filter(status = 'published')
    context = {'allPosts':allPosts}
    return render(request, 'blog/home.html', context)




def postDetail(request, post):
    post = get_object_or_404(Post, slug=post, status='published')
    comments = post.comments.filter(status=True)
    auther = request.user 
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.name = auther
            user_comment.save()
            return redirect('/' + post.slug)
        
    else:
        comment_form = CommentForm()

    context = {'post':post,'comments':comments, 'comment_form':comment_form}
    return render(request, 'blog/postDetail.html', context)




def category_list(request, category):
    category = Post.objects.filter(status = 'published', category__name=category)
    return render(request, 'blog/category_list.html', {'category':category})


def all_categories(request):
    all_categories = Category.objects.exclude(name='default')
    context = {'all_categories':all_categories,}
    return context 


def search(request):
    form = SearchForm()
    q = ''
    results = []
    if 'q' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            q = form.cleaned_data['q']
            results = Post.objects.filter(title__icontains = q)
            
    return render(request, 'blog/search.html', {'form':form, 'results':results })



@login_required(login_url='/login/')
def deletePost(request, pk):
    item = Post.objects.get(pk=pk)
    if request.user == item.auther:
        get_object_or_404(Post, pk=pk).delete()
        return redirect('/')


@login_required(login_url='/login/')
def createPost(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.auther = request.user 
            instance.save()

            return redirect('/')
    
    else:
        form = CreatePostForm()
    return render(request, 'blog/create.html', {'form':form})



@login_required(login_url='/login/')
def updatePost(request, pk):
    item = get_object_or_404(Post, pk=pk)
    if request.user == item.auther and request.method == 'POST':
        form = UpdatePostForm(request.POST,request.FILES,instance = item)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.auther = request.user 
            instance.save()
            return redirect('/')

    else:
        form = UpdatePostForm()
    return render(request, 'blog/update.html', {'form':form, 'item':item})




@unAuth_user
def register(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save() 
            messages.success(request, 'Registration successful.')
            return redirect('blog:login_user')
        else:
            messages.error(request, 'Unsuccessful registration. Invalid information.')
    
    form = NewUserForm()
    return render(request, 'blog/register.html', {'form':form})


@unAuth_user
def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f'You are logged in as {username}.')
                return redirect('blog:home')
            else:
                messages.error(request, 'Invalid username or password!')
        else:
            messages.error(request, 'Invalid username or password!')
    
    form = AuthenticationForm()
    return render(request, 'blog/login.html', {'form':form})


def logout_user(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect('/')

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>
        {% block title %}
        {% endblock title %}
    </title>

    <style>
        body{
            text-align: center;
            background-color: rgb(242, 247, 242);
            margin-bottom: 30px;
            
        }

        li{
            list-style: none;
        }
        .ourtitle{
            color:blue;
        }

        .add-post{
          margin-left: 20px;
        }
      
        .logout_login{
          margin-left: 900px;
        }

     
    </style>

    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'blog:home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% for category in all_categories %}
                    <a class="dropdown-item" href="/category/{{ category.name}}">
                    {{ category.name|title }}
                    </a>
                  
                  {% empty %}
                    <p> No category yet! </p>
                  {% endfor %}
                           
              </div>
        </li>







      <form class="form-inline my-2 my-lg-0" action="/search/" method="get">
        <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" required>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>

      <div class = 'add-post'>
        <a href="/create/"  class="btn btn-outline-success my-2 my-sm-0">Add Post</a>
        
      </div>
    
      <div class='logout_login'>
        {% if user.is_authenticated %}
        
        <li class="nav-item">
          <span><a class="nav-link" href="/logout">Logout ({{user.username}})</a></span>
        </li>
  
        {% else %}

        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        
        {% endif %}
      </div>
    </nav>

  
</nav>



    </header>
    {% block content %}

    {% endblock content %}










       <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/category_list.html
{% extends 'blog/base.html' %}

{% block title %}
    Category 
{% endblock title %}


{% block content %}


    <div class="container" style="margin-top: 30px;">
        <section class="cover">
          {% for cat in category %}
            <div style="display: inline;">
                <div class="card" style="margin-top: 25px;">
                    <div class="row no-gutters">
                        <div class="col-sm-12">
                            <div class="card-body">
                                <img src="{{ cat.image.url }}" alt="" width="500px" height="300px"><br>

                                <a href="{{ cat.get_absolute_url }}"><span class = "ourtitle"  class="card-title">{{ cat.title }}</a>[{{ cat.auther }}]</span>
                                
                                <h5 class="card-title">{{ cat.content }}</h5>
                            </div>
                        </div>
                    </div><br>
                </div>
            </div>
            {% empty %}
                <h1> No post found with this category! </h1>
           {% endfor %}
        </section>
    </div>
{% endblock content %}

blog/templates/blog/create.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}

    Create Page 
{% endblock title %}


{% block content %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}<br>
        {{ form|crispy }}
        <button type="submit" class="btn btn-dark">Add Post</button>


    </form>
{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block title %}
   HOME PAGE
{% endblock title %}


{% block content %}

    <div class="container" style="margin-top: 30px;">
        <section class="cover">
        {% if allPosts %}
          {% for post in allPosts %}
            <div style="display: inline;">
                <div class="card" style="margin-top: 25px;">
                    <div class="row no-gutters">
                        <div class="col-sm-12">
                            <div class="card-body">
                                <a href="{{ post.get_absolute_url }}" >
                                <img src="{{ post.image.url }}" alt="" width="500px" height="300px"></a><br>
                                <a href="{{ post.get_absolute_url }}"><span class = "ourtitle"  class="card-title">{{ post.title }}</a>@{{ post.auther }}</span>
                                
                                <h5 class="card-title">{{ post.content }}</h5>
                        

                                {% ifequal request.user post.auther %}
                                    <a href="delete/{{post.pk}}" style="width: 20%;" class="btn btn-danger">Delete</a>
                                    <a href="update/{{post.pk}}" style="width: 20%;" class="btn btn-success">Update</a>
                         
                                {% endifequal %}

                            </div>
                        </div>
                    </div><br>
                </div>
            </div>
           {% endfor %}
        {% else %}
            <h3>No posts yet!</h3>
        {% endif %}
        </section>
    </div>



{% endblock content %}





delete/4/delete/4/delete/4/

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Login Page 

{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-dark">Login</button>
    </form>
    <p class="text-center">Don't have an account? <a href="{% url 'blog:register' %}">Create an account</a>.</p>

{% endblock content %}

blog/templates/blog/postDetail.html
{% extends 'blog/base.html' %} 
{% load crispy_forms_tags %}

{% block title %}
    Detail Page 
{% endblock title %}


{% block content %} 


<div class="container" style="margin-top: 30px;">
    <section class="cover">
      
        <div style="display: inline;">
            <div class="card" style="margin-top: 25px;">
                <div class="row no-gutters">
                    <div class="col-sm-12">
                        <div class="card-body">
                            <img src="{{ post.image.url }}" alt="" width="500px" height="300px"><br>

                            <span class = "ourtitle" class="card-title">{{ post.title }}[{{ post.auther }}]</span>
                            
                            <h5 class="card-title">{{ post.content }}</h5><hr>
                            {% ifequal request.user post.auther %}
                                    <a href="/delete/{{post.pk}}" style="width: 20%;" class="btn btn-danger">Delete</a>
                                    <a href="/update/{{post.pk}}" style="width: 20%;" class="btn btn-success">Update</a>
                         
                                {% endifequal %}<br>

                            {% with comments.count as total_comments %}
                                {{ total_comments }} comment{{ total_comments|pluralize }}
                            {% endwith %}<br>



                            {% for comment in comments %}
                                 Comment {{ forloop.counter }} by {{ comment.name }}
                                on {{ comment.publish }}
                                {{ comment.content|linebreaks }}
                            {% empty %}
                                <p>There is no comments for this post!</p>
                            {% endfor %}
                        

                        </div>
                    </div>
                </div><br>
            </div>
        </div>
    </section>


    <form id = "myform" method="post">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <button type="submit" class="btn btn-dark">Add Comment</button>


    </form>
</div>
<script>
    $('#myform').trigger("reset");
    </script>
{% endblock content %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Register Page 

{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-dark">Register</button>
    </form>
    <p class="text-center">Have an account? <a href="{% url 'blog:login_user' %}">Login</a>.</p>

{% endblock content %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Search Page

{% endblock title %}


{% block content %}


        {% with results.count as total_results %}
             {% if total_results %}
                <h3> Found {{ total_results }} result{{ total_results|pluralize }}</h3>
            {% else %}
            <h3> Found 0 results</h3>
             {% endif %}
        {% endwith %}

       
{% for res in results %}
            



<div class="container" style="margin-top: 30px;">
    <section class="cover">
      
        <div style="display: inline;">
            <div class="card" style="margin-top: 25px;">
                <div class="row no-gutters">
                    <div class="col-sm-12">
                        <div class="card-body">
                            <a href="{{ res.get_absolute_url }}">
                                <img src="{{ res.image.url }}" alt="" width="500px" height="300px"><br>
                            </a>
                           
                            <span class = "ourtitle" class="card-title">{{ res.title }}[{{ res.auther }}]</span>
                            
                            <h5 class="card-title">{{ res.content }}</h5><hr>

                        

                        </div>
                    </div>
                </div><br>
            </div>
        </div>
    </section>

{% endfor %}




{% endblock content %}

blog/templates/blog/update.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Update Page 
{% endblock title %}



{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}<br>
        {{ form|crispy }}
        <button type="submit" class="btn btn-dark">Update</button>
    </form>
{% endblock content %}